import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HeaderTwo from "@/components/HeaderTwo";
import HomeHero from "@/components/Home/HomeHero";
import OurService from "@/components/Home/OurService";
import BestWork from "@/components/Home/BestWork";
import OurProcess from "@/components/Home/OurProcess";
import WhyUs from "@/components/Home/WhyUs";
import Testimonial from "@/components/Home/Testimonial";
import Footer from "@/components/Footer";
import Technologies from "@/components/Home/Technologies";
import Brands from "@/components/Home/Brands";
import ContactForm from "@/components/ContactForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black text-light">
        <HomeHero />
        <OurService />
        <BestWork />
        <OurProcess />
        <WhyUs />
        <Technologies/>
        <Testimonial />
        <Brands/>
        <ContactForm/>
      </main>
    </>
  );
}
